name: test_test
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: test45
        run: |
          echo "done"
        env: 
          SECRET: ${{ secrets.SECRET }}
      
      
  
